### ISSUE TITLE
Hex-file

### ISSUE THREAD

**Issue by jtronics** [cocktailyogi/EggDuino#4]
Hello,
could you upload a read Hex-File for this application.
I don't want to install the hole arduino framework, because I'm using the atmel-studio.
Thank's

**Comment by cocktailyogi** [comment]
Sorry, this it not the arduino idea and hex-file is hardware dependend. Everybody has another hardware/processor combination. You can download arduino-frame-administrative version and compile/upload it. No need to install. Yust 150megs download. Thats it.

I do not even have that hexfile, because it is compiled insitu.
